<?php
    $storeCode = $block->getStoreCode();
    $advice = $block->getAdvice();
?>
<ul class="opc-progress-bar">
    <li class="opc-progress-bar-item _active" >
        <span><?php echo __("Log in"); ?></span>
    </li>
    <li class="opc-progress-bar-item" >
        <span><?php echo __("Shipping Address"); ?></span>
    </li>
    <li class="opc-progress-bar-item">
        <span><?php echo __("Payment"); ?></span>
    </li>
</ul>
<div class="log-in">
    <div class="box login">
        <div class="inner login">
            <div class="title">
                <h3><?php echo __("Already have an account"); ?></h3>
            </div>
            <div class="conntent">
                <?php echo $this->getLayout()->createBlock("Magento\Customer\Block\Form\Login")->setTemplate("Magento_Customer::form/login.phtml")->toHtml(); ?>
                <?php echo $this->getLayout()->createBlock("Mageplaza\SocialLogin\Block\Popup\Social")->setTemplate("Mageplaza_SocialLogin::form/social.phtml")->toHtml(); ?>
            </div>
        </div>
    </div>
    <div class="box register">
        <div class="inner register">
            <div class="title">
                <h3><?php echo $advice->getTitle(); ?></h3>
            </div>
            <div class="conntent">
                <div class="inner-fix">
                    <?php echo $advice->getContent(); ?>
                    <div class="toolbar">
                        <div class="primary">
                            <a href="<?php echo $storeCode; ?>/customer/account/create/" class="action create primary">
                                <span><?php echo __("Create an Account"); ?></span>
                            </a>
                        </div>
                        <div class="or">
                            <span class="label"><?php echo __("or continue as a guest"); ?></span>
                        </div>
                        <div class="go-to-checkout">
                            
                        <div class="primary">
                                <a href="<?php echo $storeCode; ?>/checkout/" class="action primary checkout">
                                    <span class="label"><?php echo __("Buy without registration"); ?></span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="actions-toolbar" id="shipping-method-buttons-container">
    <div class="primary">
        <button type="submit" class="button action continue primary">
            <span data-bind="i18n: 'Next'">Next</span>
        </button>
    </div>
</div>
